function varargout = TDTmultimap(probename)
%------------------------------------------------------------------------
% ChannelMap = TDTmultimap(probename)
%------------------------------------------------------------------------
% TytoLogy:Experiments:opto
%------------------------------------------------------------------------
%	Mapping for TDT 18 pin DIP interface to Multielectrode probes
%	see TDT_MultiElectrode_Map.xlsx for details
%------------------------------------------------------------------------
%	probename	probe id, e.g., A1X16 for the neuronexus A1X16 probe
% 	ChannelMap	index to A/D channels organized by increasing depth
%------------------------------------------------------------------------

%------------------------------------------------------------------------
% Sharad Shanbhag 
% sshanbhag@neomed.edu
%------------------------------------------------------------------------
%------------------------------------------------------------------------
% Created:	17 Sep 2019 (SJS)
%
% Revisions
%------------------------------------------------------------------------
tmpP = probeinfo;
if ~isfield(tmpP, probename)
	error('%s: unknown field %s', mfilename, probename)
else
	P = tmpP.(probename);	
end

% need to reorder A1X16.channel in reverse so that the first channel in the
% index is the deepest
ChannelMap = P.ADchannel(P.depth_index);
varargout{1} = ChannelMap;
varargout{2} = P;

end

function P = probeinfo

% # of sites per shaft
A1X16.sites_per_shaft = 16;
A1X16.nshafts = 1;
% ordering of sites along shaft (top to bottom)
% this corresponds to pins on the electrode DIP connector
A1X16.sites	=		[	9, ...
							8, ...
							10, ...
							7, ...
							13, ...
							4, ...
							12, ...
							5, ...
							15, ...
							2, ...
							16, ...
							1, ...
							14, ...
							3, ...
							11, ...
							6	];
% Corresponding A/D channel for TDT hardware (using DIP to ZIF adapter,
% 16 channel ZIF headstage). Use this for indexing into the 16 channels
% from probe.
A1X16.ADchannel	=	[	16, ...
								1, ...
								15, ...
								2, ...
								12, ...
								5, ...
								13, ...
								4, ...
								10, ...
								7, ...
								9, ...
								8, ...
								11, ...
								6, ...
								14, ...
								3	];
% depth information
% this is index from top (shallowest site) to bottom (deepest site)
A1X16.depth_index = 16:-1:1;
% offset of deepest site from tip of probe
A1X16.depth_offset = 50;
% spacing between sites, micrometers
% typically 25, 50, 100, 200
A1X16.spacing = 100;
% total span of recording sites, um
A1X16.span = A1X16.sites_per_shaft * A1X16.spacing;

P.A1X16 = A1X16;

end

